### ISSUE TITLE
Impact of Node V14

### ISSUE THREAD

**Issue by abidsaigol** [mscdex/ssh2-streams#172] opened 2021-05-10 18:23 UTC
I use the SFTP extension to Visual Studio Code, and a recent update to VS Code upgraded the app to V14 of Node. With this change, the SFTP extension stopped working.  It would seem that the problem encountered by the extension is related to your SSH2-Streams package that the extension uses as a dependency.

I want to bring to your attention this comment as it may be something that you may want to address in your code:
https://github.com/liximomo/vscode-sftp/issues/919#issuecomment-836005639

If this isn't relevant to the proper functioning of your package, then I apologize for any inconvenience caused by my posting this issue.

**Comment by mscdex** [comment] 2021-05-10 22:17
Duplicate of https://github.com/mscdex/ssh2/issues/1007.

**Closed as completed by mscdex** 2021-05-10 22:17 UTC
Labels: duplicate
