### ISSUE TITLE
When downloading a large file over sftp, the 65536th byte is always dropped.

### ISSUE THREAD

**Issue by paulroth3d** [mscdex/ssh2-streams#43] opened 2016-07-14 14:33 UTC
High level, this fix addresses an issue where when downloading a large file
(greater than 65535 bytes), the 65536th byte is dropped on each buffer)
Meaning zips - etc cannot be opened.

-- I have a fix for this (pull #42 ) that i've confirmed with my own project.
Please do take a look as quickly as possible.
## 

The highest number should be 65535 not 65536.
The reason is that we are dealing with unsigned digits
and 65535 in binary is 0b1111111111111111
(this is the full integer with all 1s)

65536 in binary is just one more 0b10000000000000000

When downloading large files, what happens is that the buffer
THINKs it stores 65536 bytes, but actually only stores 65535
(and the 65536th byte is lost for each buffer)

Correcting the issue to 64*1024-1 (65535) makes sure that the
highest number of bytes actually meets what it can store.

https://github.com/mscdex/ssh2-streams/pull/42

**Comment by paulroth3d** [comment] 2016-07-14 14:36
@mscdex - I greatly appologize for being a pest.
Could you please look into folding this in when you can?

(I understand I just put in this request, but i don't tend to see them - for my own things) unless I'm @mentioned.  I am very sorry if you've gotten too many pings.)

**Comment by paulroth3d** [comment] 2016-07-14 19:21
Moving the conversation to the pull request #42

**Comment by BorePlusPlus** [comment] 2016-09-23 16:38
I have observed same behaviour. I "fixed" it by setting `highWaterMark` at less than 64 * 1024. Let me add more information to PR.

**Comment by joeyhub** [comment] 2017-01-25 16:36
If it's an issue with the server brought about by defaults in my opinion the fix should just be to expose that setting somewhere and let people override/fix then maybe link to this issue for the configuration option in the usage doc or something if being really kind.

**Comment by mscdex** [comment] 2017-05-28 23:24
Closing this for now. If someone is able to create a setup that I can use to easily reproduce the problem locally (e.g. docker setup or otherwise), then I am willing to give that a shot. Otherwise there is not much that I can do at this point. The `highWaterMark` is already configurable if you want to override the default.

**Closed by mscdex** 2017-05-28 23:24 UTC

**Comment by sadams** [comment] 2018-03-10 09:56
I know i'm late to the party here, but FWIW I was just bitten by the same problem. I tried to improve speed when downloading a large file over SFTP by increasing the `highWaterMark` in `createReadStream`, but found that increasing it above 64k started to reduce the size of the file streamed to disk (with every increase of HWM the bytes streamed decreased).
These are the idents:
DEBUG: Local ident: 'SSH-2.0-ssh2js0.1.20'
DEBUG: Remote ident: 'SSH-2.0-OpenSSH_6.7p1 Debian-5'

(PS: maybe changing HWM is not the right solution to improve speed, but I was finding downloading was ~5x slower than using `scp`, for example).

**Comment by mscdex** [comment] 2018-03-10 18:04
@sadams for the best performance, you'll want to use something like `fastGet()`/`fastPut()` if you're downloading to disk/uploading from disk respectively.

**Comment by sadams** [comment] 2018-03-10 20:25
Thanks for the suggestion but I’m trying to avoid holding the whole file on disk (I’m doing ETL on a large file and just need to process it and upload it back out again). Possibly node isn’t the best solution for my use case.

**Comment by nemozny** [comment] 2019-03-04 08:57
@mscdex You can easily replicate the issue now, using Visual Studio Code with vscode-remote plugin. All files get truncated after 65535 bytes. Your package is bundled in ssh2-sftp-client. See the reference above "Partial loading of big files...".

**Comment by jnsbal** [comment] 2019-07-30 16:14
I can confirm the issue still persists. With fastGet it works for me everytime
